# Generated by Django 4.2.7 on 2023-12-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipmalpha', '0017_alter_project_options'),
        ('finance', '0003_alter_transaction_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='ipmalpha.project', verbose_name='Project'),
        ),
    ]
