# Generated by Django 4.2.7 on 2023-11-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmalpha', '0002_alter_project_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
