# Generated by Django 4.2.7 on 2023-12-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0004_client_slug'),
        ('ipmalpha', '0007_remove_project_project_client_project_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_client',
        ),
        migrations.AddField(
            model_name='project',
            name='project_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ipmclients.client'),
        ),
    ]
