# Generated by Django 4.2.7 on 2023-12-11 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipmalpha', '0014_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
