# Generated by Django 4.2.7 on 2023-12-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmalpha', '0015_alter_project_project_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
