# Generated by Django 4.2.7 on 2023-12-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmalpha', '0016_remove_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pk'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
