# Generated by Django 4.2.7 on 2023-12-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0020_alter_client_client_name'),
        ('ipmalpha', '0018_alter_project_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ipmclients.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(default='Draft', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipmalpha.status'),
        ),
    ]
