# Generated by Django 4.2.7 on 2023-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmalpha', '0019_alter_project_project_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
