# Generated by Django 4.2.7 on 2023-11-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_agreements',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_contact',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_roletype',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_telegram',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
