# Generated by Django 4.2.7 on 2023-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0002_client_client_agreements_client_client_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_active',
            field=models.BooleanField(default=True),
        ),
    ]
