# Generated by Django 4.2.7 on 2023-11-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0003_client_client_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
