# Generated by Django 4.2.7 on 2023-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0006_alter_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=512), max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
