# Generated by Django 4.2.7 on 2023-12-11 21:52

import autoslug.fields
import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0014_alter_client_newslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='newslug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=builtins.id),
        ),
    ]
