# Generated by Django 4.2.7 on 2023-12-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0015_alter_client_newslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='newslug',
        ),
    ]
