# Generated by Django 4.2.7 on 2023-12-11 22:03

import autoslug.fields
import builtins
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0016_remove_client_newslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='newslug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from=builtins.id, unique=True),
        ),
    ]
