# Generated by Django 4.2.7 on 2023-12-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0018_remove_client_newslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
    ]
