# Generated by Django 4.2.7 on 2023-12-29 23:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0020_alter_client_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, null=True, region=None),
        ),
    ]
