# Generated by Django 4.2.7 on 2023-12-30 15:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0021_alter_client_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU'),
        ),
    ]
