# Generated by Django 4.2.7 on 2023-12-30 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ipmclients', '0022_alter_client_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_closed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
